language: node_js
node_js:
- '6'
deploy:
  api_key:
    secure: V8oNqJwmNPbRaGeovI8RC84VVtAByyLgpOuosKaDOULj/ToZR2JmS8btjQNKHBERcgaCZJiAZErDEyn+k3hAp02kv4j+tR8WKfD1Xbf3XXMe3xaSNa+5x8aoS8SgjXQFr7rpqkyisH+Rtri4Ue+9FoORZ+Odv7nbI2SnWY0p3mTk3egJBW8g4SjuBVp5m0RIr/tYJdAIONZlmLiIm7eEGepYjx+tBPJ8fzwkc6PH0eAP0j+QX9QMEr6RL+86yLnEqXzPZL0XvYnDLXSCWTOnSEL1q+n8JnBqY765R4OLQluxIaXf+YDt//azw3xgd1vlD1guV0d+nrJtzymvWEP4FIdelgmaTpV+kwlcEgHk28sy9Zi4k2sscyu7vXww6APH0EQe1XKZSRtoq1jcsWJcoJfQvbHItCu2k/VSEkjlBw82egxFnjxyZkYngIMLecFdC6bZplHkBZYkzI8k7YkbqeztyVY4wgBac690urt4RoJxh2eh0Pv2merJE3Q4uarDjmxw4FqRD+6rGCep+jnfEO4Ce8PNHxMfYF3Yip0WV1UQI+mLBFxgRFAgMIcacJBPu0FTOm2orEwNrxXjeb4SU1o204gMTDeydWTQ8D3CFpp3g0z0MebMP3idjYyEBgRou3xNY8GuU2V48mFO8evQ4sLz80mvLuoK7nM7nTLIl4U=
  email: julian@dotcore.co.il
  provider: npm
  on:
    tags: true
after_script:
- npm run coveralls
services:
- redis-server
